### ISSUE TITLE
Why does `PageNode` implements `ExportMixin`

### ISSUE THREAD

**Issue by softmarshmallow** [figma/plugin-typings#100]
Page cannot be exported. why does PageNode implements ExportMixin ?

or.. can it be? - if yes - how?

**Comment by zyumbik** [comment]
A page can be exported. If you want to do it via the editor, you can deselect everything and in the right panel you will see export settings for the page.

**Comment by softmarshmallow** [comment]
Did not know !

Thanks a lot
