### ISSUE TITLE
Cannot augment module 'console'

### ISSUE THREAD

**Issue by florianb** [figma/plugin-typings#101]
I have no clue why this error pops up or why my setup seems to be the only one complaining about this. The only fix i could imagine was adding a `@ts-ignore` above the `index.d.ts:11:9`.

```
node_modules/@figma/plugin-typings/index.d.ts:11:9 - error TS2649: Cannot augment module 'console' with value exports because it resolves to a non-module entity.

11   const console: Console
           ~~~~~~~
```

**Comment by zyumbik** [comment]
Probably related: 

https://github.com/figma/plugin-typings/issues/96

https://github.com/figma/plugin-typings/issues/90

**Comment by florianb** [comment]
Thank you @zyumbik – i fixed it adding

```
...
    "skipLibCheck": true,
...
```

to my `tsconfig.json`.

**Comment by florianb** [comment]
No clue if this is how things should work in the TS world. :smiling_face_with_tear:
