### ISSUE TITLE
Could we ever know value contained in mixed return value?

### ISSUE THREAD

**Issue by softmarshmallow** [figma/plugin-typings#14]
https://www.figma.com/plugin-docs/api/properties/figma-mixed/

if mixed returned, let's say font size as in the docs.
Can we ever get, at least, array of numbers of the text's font size?

**Comment by zyumbik** [comment]
You can get them character by character: https://www.figma.com/plugin-docs/api/TextNode/#text-range-functions

**Comment by softmarshmallow** [comment]
That will do the magic. Thanks a lot.
