### ISSUE TITLE
resize() function not taking variables

### ISSUE THREAD

**Issue by brankoo124** [figma/plugin-typings#150]
Hi, I am trying to resize line node.

`const rowLine = figma.createLine();`
`rowLine.resize(908, 1);`

When I add number variables it gives me this error message:
![image](https://user-images.githubusercontent.com/51480413/189706336-f76c5fc4-2ad5-4efa-96b4-24ce54fc5a67.png)

Is there some mistake in function or am I using it wrong?

**Comment by zyumbik** [comment]
The line always has the heigh of 0, you can't change it.
