### ISSUE TITLE
Syntax error on line 48: Unexpected token export {};

### ISSUE THREAD

**Issue by tharunkmr3** [figma/plugin-typings#192]
I am trying use:

import nlp from 'compromise/three';

But it shows the below error:
Syntax error on line 48: Unexpected token export {};

How do I fix this?

**Comment by ymichael** [comment]
Hi @tharunkmr3, for plugin related help, I recommend joining the discord server and asking there: https://www.figma.com/plugin-docs/get-help/ 

I'm going to close this out since this isn't an issue related to plugin-typings
