### ISSUE TITLE
No typings for fetch() signal parameter

### ISSUE THREAD

**Issue by alexincore** [figma/plugin-typings#207]
Interface `FetchOptions` is missing a `signal` parameter of type AbortSignal, which is used to provide a timeout for the fetch request https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout

```
  interface FetchOptions {
    method?: string
    headers?: { [name: string]: string }
    /**
     * @deprecated use headers instead
     */
    headersObject?: { [name: string]: string }
    body?: Uint8Array | string
    credentials?: string
    cache?: string
    redirect?: string
    referrer?: string
    integrity?: string
  }
```

**Comment by darknoon** [comment]
Is `AbortSignal` / cancellation implemented in Figma?

**Comment by james04321** [comment]
AbortSignal is not supported in the plugin sandbox, so the typings are correct here.
