### ISSUE TITLE
Cannot change STICKY size using `resize` method

### ISSUE THREAD

**Issue by tonexu** [figma/plugin-typings#216]
Hi, I am trying to create some STICKY of different width and height (not 200X200) using API for my widget.

As suggested in [StickyNode | Plugin API](https://www.figma.com/plugin-docs/api/StickyNode/), width and height of sticky are all [read only] and I should use resize method. So my code was sticky.resize(item.width, item.height); but I got an error message `Property 'resize' does not exist on type 'StickyNode'.`

Also on [Shared Node Properties | Plugin API](https://www.figma.com/plugin-docs/api/node-properties) , neither “resize” nor " resizeWithoutConstraints" section on this page includes stickyNodes.

**Comment by glebsexy** [comment]
It seems like sticky nodes can't be resized, they can only be rescaled (equivalent to using a scale tool).

**Comment by glebsexy** [comment]
Sticky nodes can't be resized to arbitrary width/height. They can only be square or a specific rectangular shape: you can change between the two using the `isWideWidth` property which **doesn't seem to be documented or included in the typings** but it can be used in Figma/FigJam. 

Example: `figma.currentPage.selection[0].isWideWidth = true` sets selected sticky node to have a rectangular shape.
