### ISSUE TITLE
Gradient Paint does not contain data of its start/end positions

### ISSUE THREAD

**Issue by piusyikyu** [figma/plugin-typings#219]
Hi devs,

I am trying to fetch the gradient paint object but it does not include the start and end positions.

Many thanks

![image](https://github.com/figma/plugin-typings/assets/42695673/8549125f-a9c6-4834-8c68-f85909189d1f)

**Comment by glebsexy** [comment]
You don't need them. Use gradientTransform.

https://forum.figma.com/t/need-help-with-gradienttranform-matrix/26792/

**Comment by Roystbeef** [comment]
haven't tested this but [extractLinearGradientStartEnd.ts](https://github.com/figma-plugin-helper-functions/figma-plugin-helpers/blob/5f3a767212da804054dbb97e0c39c161c5b03f22/src/helpers/extractLinearGradientStartEnd.ts) may be useful here?

**Comment by piusyikyu** [comment]
I will take a look thanks
