### ISSUE TITLE
Bug: Added fields were removed again

### ISSUE THREAD

**Issue by lukasoppermann** [figma/plugin-typings#234]
Hey, I think @rohitchouhan8 did not rebase before merging his PR https://github.com/figma/plugin-typings/commit/533d2ad08a95f7b6f2261b019c6ae54b58ad2b55

And this is why it deleted the fields that were re-added in this [PR](https://github.com/figma/plugin-typings/commit/c70763b6756d8b265b7bb406fc607d5790b14ed9) by @RobbieZhuang

**Comment by elainefigma** [comment]
Thanks for flagging! This PR added the fields back - https://github.com/figma/plugin-typings/pull/235
The types should be available in the latest plugin-typings version, 1.71.1.

Apologies for the confusion here.
