### ISSUE TITLE
Typings are missing a license

### ISSUE THREAD

**Issue by KyleWpppd** [figma/plugin-typings#24]
Hi,

I'd like to use these typings for a work project, but my employer requires a license for any imported code.

Could you add a `LICENSE` file with whichever license covers the typings? 

I've linked the Apache 2 license because it's often used for typings: http://www.apache.org/licenses/LICENSE-2.0.txt

Thank you,
Kyle

**Comment by emartinfigma** [comment]
Fixed in #32.
