### ISSUE TITLE
TextNode support add a hyperlink

### ISSUE THREAD

**Issue by ChenSWD** [figma/plugin-typings#29]
I want to add a hyperlink to text，but I can't find a function to set

**Comment by james04321** [comment]
This is already supported by the `hyperlink` property, or using `setRangeHyperlink()`:

https://www.figma.com/plugin-docs/api/TextSublayer/#hyperlink
https://www.figma.com/plugin-docs/api/TextSublayer/#setrangehyperlink

To demonstrate, select any text node, and run:

```js
figma.currentPage.selection[0].hyperlink = { type: 'URL', value: 'https://www.google.com' }
```
