### ISSUE TITLE
Typo in NodeChangeProperty: 'stokeTopWeight' instead of 'strokeTopWeight'

### ISSUE THREAD

**Issue by andreincu** [figma/plugin-typings#302]
https://github.com/figma/plugin-typings/blob/b74f8207eab4ea94fa36646598e9eaca25756b19/plugin-api.d.ts#L650

**Comment by jefflee-figma** [comment]
Thanks for a report. This is a known issue that we have kept around for backward compatability. See the note here: https://www.figma.com/plugin-docs/api/NodeChangeProperty/
