### ISSUE TITLE
 Argument of type '"drop"' is not assignable to parameter of type 'ArgFreeEventType'

### ISSUE THREAD

**Issue by jk2K** [figma/plugin-typings#306]
No overload matches this call.
  The last overload gave the following error.
    Argument of type '"drop"' is not assignable to parameter of type 'ArgFreeEventType'

@figma/plugin-typings version 1.99.0

**Comment by efrankenbergfigma** [comment]
> ArgFreeEventType

Hi! Could you provide any more information about the error you're seeing? We have a plugin-samples plugin that utilizes this event [here](https://github.com/figma/plugin-samples/blob/master/icon-drag-and-drop/code.ts) and you can take a look at how you can correctly use. Thanks!

**Comment by jk2K** [comment]
<img width="954" alt="image" src="https://github.com/user-attachments/assets/a7e98ac3-9bf2-4acf-9b54-1ea194654454">

<img width="526" alt="image" src="https://github.com/user-attachments/assets/7fd694db-12d4-4a20-800e-7919890b4641">



tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "es6"
    ],
    "strict": true,
    "typeRoots": [
      "../node_modules/@figma",
      "../node_modules/@types"
    ],
    "moduleResolution": "node",
    "esModuleInterop": true,
  }
}
```

**Comment by glebsexy** [comment]
It's a separate function type defined here:
https://github.com/figma/plugin-typings/blob/master/plugin-api.d.ts#L51C3-L53C66

<img width="556" alt="image" src="https://github.com/user-attachments/assets/0a5d42c3-118f-411f-89db-1ffa3f4446e1">

Are you sure your typings are up to date? Run `npm i --save-dev @figma/plugin-typings@latest` just to make sure.

**Comment by jk2K** [comment]
thanks, fixed it, my function not return a boolean,
