### ISSUE TITLE
「GET/v1/component_sets/:key」The result is wrong

### ISSUE THREAD

**Issue by justquanyin** [figma/plugin-typings#318]
When try get 「GET/v1/component_sets/:key」 endpoint ， the result is 404

I call 「Get file」 endpoint ，get the componetSets key ， and call 「GET/v1/component_sets/:key」pass the key , But the result is 404

Example

<img width="563" alt="image" src="https://github.com/user-attachments/assets/00a2bc08-f9d9-4a68-9809-6722425401c5">

<img width="686" alt="image" src="https://github.com/user-attachments/assets/28c42bf0-05f1-46cf-a6eb-172437eb34b9">

**Comment by grace-figma** [comment]
Hi! This is an issue for the Rest API, will consolidate the conversation there!
