### ISSUE TITLE
[BUG] DestinationId does not exist on type Action

### ISSUE THREAD

**Issue by pantelispanayiotou** [figma/plugin-typings#46]
I am trying to destructure destinationId from Action and i receive the following: 
Property 'destinationId' does not exist on type 'Action'.
Property 'destinationId' does not exist on type '{ readonly type: "BACK" | "CLOSE"; }'

**Comment by cyberalien** [comment]
That's not a bug, you need to make sure property `type` is correct before destructuring. For example, like this:

```js
switch (action.type) {
  case 'NODE': {
    const destinationId = action.destinationId;
    /// ... do your stuff

    break;
  }
    
}
```
or
```js
if (action.type !== 'NODE') {
  return;
}

// Now that all types except 'NODE' have been excluded, you should be able to destructure it
const { destinationId } = action;
```

If you do `type` validation, there won't be an error.

If you don't want to do `type` validation, you can force type like this:
```js
const { destinationId } = (action as unknown) as Record<string, string | null>;
```
which should result in `destinationId` being string, null or undefined, just like it would if TypeScript allowed you to destructure without validating `type` property.

**Comment by isg** [comment]
thanks @cyberalien and @pantelispanayiotou!
