### ISSUE TITLE
interface CurrentUser support?

### ISSUE THREAD

**Issue by L-Jovi** [figma/plugin-typings#78]
Hi, I found current release not include `figma.CurrentUser` defined in `index.d.ts`

I notice [pr#59](https://github.com/figma/plugin-typings/pull/59) add above defination, but it's missing now.

Would you mind check the problem?

Thx for your time :)

**Comment by jlai-figma** [comment]
Hi!  We haven't officially released this API yet, please stay tuned for a future release when we officially announce it.  Thanks!
