### ISSUE TITLE
Constraints are missing in GroupNode

### ISSUE THREAD

**Issue by k15a** [figma/plugin-typings#91]
It's possible to change the constraints for a group in the properties panel but the plugin types and the plugin API don't include them.

<img width="236" alt="Screen Shot 2021-11-12 at 16 58 04" src="https://user-images.githubusercontent.com/20357450/141496346-1c3fe7c5-49ba-4602-8433-875afe22a1bb.png">

**Comment by jefflee-figma** [comment]
Thanks for the bug report. The Plugin API now has the ability to iterate over group node constraints. Please see:

https://www.figma.com/plugin-docs/api/GroupNode/#applying-constraints-to-groups
