### ISSUE TITLE
New line characters are not included in TextNode.characters

### ISSUE THREAD

**Issue by k15a** [figma/plugin-typings#92]
**Reproduction:**

- Create a text with a new line (Shift + Enter) and a paragraph (Enter)

<img width="278" alt="Screen Shot 2021-11-12 at 17 06 07" src="https://user-images.githubusercontent.com/20357450/141497424-b80ad306-fcc3-4b35-8a16-94c46d538f8d.png">

- Inspect the TextNode in the console with (inside a plugin):

```js
for (const node of figma.currentPage.selection) {
  console.log(node)
}
```

- `TextNode.characters` does not contain new lines and paragraphs are converted to new lines instead:

<img width="400" alt="Screen Shot 2021-11-12 at 17 01 40" src="https://user-images.githubusercontent.com/20357450/141497561-ea6ad257-81ec-461a-8a5c-bdf832491462.png">

Is there a way to get new lines of a TextNode?

**Comment by cyberalien** [comment]
If you are using OSX, shift+enter creates soft line break, not `\n`. Character is `String.fromCodePoint(8232)`

**Comment by k15a** [comment]
> If you are using OSX, shift+enter creates soft line break, not \n. Character is String.fromCodePoint(8232)

Ohh, my bad. Thank you!
