### ISSUE TITLE
Cannot find name 'figma'.

### ISSUE THREAD

**Issue by kopyl** [figma/plugin-typings#94]
When I compile ts via ```tsc code.ts``` i get

```
code.ts:9:1 - error TS2304: Cannot find name 'figma'.

9 figma.showUI(__html__);
  ~~~~~

code.ts:9:14 - error TS2304: Cannot find name '__html__'.

9 figma.showUI(__html__);
               ~~~~~~~~

code.ts:14:1 - error TS2304: Cannot find name 'figma'.

14 figma.ui.onmessage = msg => {
   ~~~~~

code.ts:18:18 - error TS2304: Cannot find name 'SceneNode'.

18     const nodes: SceneNode[] = [];
                    ~~~~~~~~~

code.ts:20:20 - error TS2304: Cannot find name 'figma'.

20       const rect = figma.createRectangle();
                      ~~~~~

code.ts:23:7 - error TS2304: Cannot find name 'figma'.

23       figma.currentPage.appendChild(rect);
         ~~~~~

code.ts:26:5 - error TS2304: Cannot find name 'figma'.

26     figma.currentPage.selection = nodes;
       ~~~~~

code.ts:27:5 - error TS2304: Cannot find name 'figma'.

27     figma.viewport.scrollAndZoomIntoView(nodes);
       ~~~~~

code.ts:32:3 - error TS2304: Cannot find name 'figma'.

32   figma.closePlugin();
     ~~~~~


Found 9 errors.
```

Could you please fix it?

I installed the typings. My tsconfig looks like this:

```{
  "compilerOptions": {
    "target": "es6",
    "lib": ["es6"],
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/@figma"
    ]
  }
}```

**Comment by zyumbik** [comment]
Simply run `tsc` instead of `tsc code.ts`, otherwise you need to also specify your tsconfig.json, so the full explicit command would be `tsc code.ts -p tsconfig.json`.

**Comment by kopyl** [comment]
> Simply run `tsc` instead of `tsc code.ts`, otherwise you need to also specify your tsconfig.json, so the full explicit command would be `tsc code.ts -p tsconfig.json`.

Thanks a lot, that fixed the issue. I'm surprised I'm the first who posted in "[issues](https://github.com/figma/plugin-typings/issues)"

**Comment by cvinuale** [comment]
> Simply run `tsc` instead of `tsc code.ts`, otherwise you need to also specify your tsconfig.json, so the full explicit command would be `tsc code.ts -p tsconfig.json`.

thank you so much I was getting crazy!
