### ISSUE TITLE
VSCode linter broken in 1.39.0

### ISSUE THREAD

**Issue by imaustink** [figma/plugin-typings#95]
The TS linter in VScode is unable to find any types from this library as of version `1.39.0`.
![image](https://user-images.githubusercontent.com/6282922/142559880-c0342dd9-e490-4e6d-bff5-792ee72fc338.png)
Downgrading to `1.38.0` solves the issue.
![image](https://user-images.githubusercontent.com/6282922/142559844-e7941f6b-8286-4653-b57c-047007ad83f5.png)

Strangely, I am still able to compile source using types from this package at version 1.39.0, but the linter can't pick them up.

**Comment by ymichael** [comment]
Sorry about this, you should be able to fix this by running

```
npm install @figma/plugin-typings@latest
```

to pick up the hot fix for this issue. Thanks for reporting!
