### ISSUE TITLE
Issues with `console` typings

### ISSUE THREAD

**Issue by ymichael** [figma/plugin-typings#96]
See: https://github.com/figma/plugin-typings/issues/90#issuecomment-976694005

11   const console: Console
           ~~~~~~~

  ../../../../usr/local/lib/node_modules/typescript/lib/lib.dom.d.ts:19124:13
    19124 declare var console: Console;
                      ~~~~~~~
    'console' was also declared here.

../../../../usr/local/lib/node_modules/typescript/lib/lib.dom.d.ts:19124:13 - error TS2451: Cannot redeclare block-scoped variable 'console'.

19124 declare var console: Console;
                  ~~~~~~~

  node_modules/@figma/plugin-typings/index.d.ts:11:9
    11   const console: Console
               ~~~~~~~
    'console' was also declared here.

Found 2 errors.

**Comment by ymichael** [comment]
cc @glassesUSA

**Comment by glassesUSA** [comment]
```{
  "compilerOptions": {
    "target": "es6",
    "skipLibCheck": true,
    "lib": [
      "es6",
      "dom",
      "es2017"
    ],
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/@figma"
    ]
  }
}`

tsconfig - with the skip lib check it works

**Comment by ymichael** [comment]
ah lib should be es6 for plugin api code:

```
    "lib": ["es6"],
```

**Comment by fwextensions** [comment]
Why is `"skipLibCheck": true` still necessary?  I'm using `@figma/plugin-typings` 1.76.0, and it generates TS2451 errors for `console` and `fetch`.  The `"es6"` lib seems unrelated.  It works fine with `"es2020"`, as long as `skipLibCheck` is set.

I'm no TS expert, but this sure seems like a problem with how the Figma typings file is set up.  All `skipLibCheck` is doing is suppressing the error message.

**Comment by tmcw** [comment]
Seconding that, I updated to [support the async APIs](https://www.figma.com/plugin-docs/migrating-to-dynamic-loading/) and was was greeted by some new type errors like this:

```
node_modules/.pnpm/@types+node@20.11.27/node_modules/@types/node/globals.d.ts:370:14 - error TS2451: Cannot redeclare block-scoped variable 'fetch'.

370     function fetch(
                 ~~~~~

  node_modules/.pnpm/@figma+plugin-typings@1.88.0/node_modules/@figma/plugin-typings/index.d.ts:27:9
    27   const fetch: (url: string, init?: FetchOptions) => Promise<FetchResponse>
               ~~~~~
    'fetch' was also declared here.

node_modules/.pnpm/typescript@5.4.2/node_modules/typescript/lib/lib.dom.d.ts:28148:18 - error TS2451: Cannot redeclare block-scoped variable 'fetch'.

28148 declare function fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response>;
                       ~~~~~

  node_modules/.pnpm/@figma+plugin-typings@1.88.0/node_modules/@figma/plugin-typings/index.d.ts:27:9
    27   const fetch: (url: string, init?: FetchOptions) => Promise<FetchResponse>
               ~~~~~
    'fetch' was also declared here.
```

`@types/node` is in my node_modules because `vitest` requires it.
